FROM python:alpine

COPY requirements-crawler.txt /requirements.txt
RUN pip install -r requirements.txt

COPY ./crawler.py /search_engine/crawler.py
WORKDIR /search_engine

ENTRYPOINT ["python", "-u", "crawler.py"]