FROM python:alpine

COPY requirements-web.txt /requirements.txt
RUN pip install -r requirements.txt

COPY ./search.py /search_engine/search.py
WORKDIR /search_engine
ENV FLASK_APP=search.py

ENTRYPOINT ["gunicorn", "search:app", "-b", "0.0.0.0"]